stages:
  - test
  - analyze
  - archive
  - deploy

unit_test:
  stage: test
  script:
    - flutter test -v --coverage
    - lcov --list coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  except:
    - master
  artifacts:
    paths:
      - coverage
  tags:
    - mac-mini

analyze:
  stage: analyze
  script:
    - flutter analyze -v
  except:
    - master
  tags:
    - mac-mini

archive_android_debug:
  stage: archive
  script:
    - flutter build apk --debug --target="lib/main_mobile.dart" -v
  except:
    - master
    - develop
  artifacts:
    expire_in: 60min
    paths:
      - build/app/outputs/apk/debug/app-debug.apk
  tags:
    - mac-mini

archive_ios_debug:
  stage: archive
  script:
    - flutter build ios --debug --target="lib/main_mobile.dart" -v
    - cd build/ios/iphoneos/
    - mkdir -p Payload
    - mv Runner.app Payload/
    - zip -ry Runner.ipa Payload
  except:
    - master
    - develop
  artifacts:
    expire_in: 60min
    paths:
      - build/ios/iphoneos/Runner.ipa
  tags:
    - mac-mini

archive_android_release:
  stage: archive
  script:
    - flutter build apk --target="lib/main_mobile.dart" -v
  only:
    - develop
  artifacts:
    expire_in: 30min
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - mac-mini

archive_ios_release:
  stage: archive
  script:
    - flutter build ios --target="lib/main_mobile.dart" -v
    - cd build/ios/iphoneos/
    - mkdir -p Payload
    - mv Runner.app Payload/
    - zip -ry Runner.ipa Payload
  only:
    - develop
  artifacts:
    expire_in: 30min
    paths:
      - build/ios/iphoneos/Runner.ipa
  tags:
    - mac-mini

archive_web_develop:
  stage: archive
  script:
    - flutter build web --target="lib/main_web.dart" -v
  only:
    - develop
  artifacts:
    expire_in: 30min
    paths:
      - build/web
  tags:
    - mac-mini

deploy_mobile:
  stage: deploy
  script:
    - mkdir .public
    - cp -r html/index.html .public
    - cp -r html/app.plist .public
    - cp -r build/app/outputs/apk/release/app-release.apk .public
    - cp -r build/ios/iphoneos/Runner.ipa .public
    - mv .public public
  dependencies:
    - archive_android_release
    - archive_ios_release
  artifacts:
    paths:
      - public
  only:
    - develop
  tags:
    - mac-mini

deploy_web_develop:
  stage: deploy
  script:
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --token ${FIREBASE_TOKEN} --only hosting
  dependencies:
    - archive_web_develop
  only:
    - develop
  tags:
    - mac-mini
