image: kitproject/gitpod-flutter:v1.24.0-10.2.pre
tasks:
  - init: >
      sudo apt-get update && sudo apt-get upgrade -y && 
      flutter channel beta && flutter upgrade && flutter config --enable-web && 
      flutter pub get
    command: >
      flutter run --web-port=8080 --web-hostname=0.0.0.0 --target="lib/main_web.dart" -v
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - Dart-Code.dart-code@3.7.1:3XT4xvtPoRdNasA5smNMiA==
    - Dart-Code.flutter@3.7.1:gujVOCgsbgoN2/po8X1tfA==
    - alphabotsec.vscode-eclipse-keybindings@0.10.0:sHFK2cBlpLZsoaR/+m8Nig==
