name: idea_note
description: Idea note app.

version: 0.1.0+1000

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.14.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_sheet_localization: ^1.0.0
  font_awesome_flutter: ^8.7.0
  provider: ^4.0.4
  shared_preferences: ^0.5.6+2
  sembast: ^2.2.0+1
  sembast_web: ^1.0.0

  flutter_speed_dial: ^1.2.5
  smooth_page_indicator: ^0.1.3

  path_provider: ^1.6.1
  package_info_wrapper:
    git: https://gitlab.com/kitProject/package_info_wrapper.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
  flutter_sheet_localization_generator: ^1.2.0
  build_runner: ^1.7.4

dependency_overrides:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
