name: idea_note
description: Idea note app.

version: 0.1.0+1000

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.14.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_sheet_localization: ^1.0.0
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.6.0
  provider: ^4.0.3

  flutter_speed_dial: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
  flutter_sheet_localization_generator: ^1.2.0
  build_runner: ^1.7.4

dependency_overrides:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
