name: idea_note
description: Idea note app.

version: 0.1.0+1000

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.13.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_sheet_localization: ^1.0.0
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.5.1
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0
  flutter_sheet_localization_generator: ^1.2.0
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
