name: idea_note
description: Idea note app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.13.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_sheet_localization: ^1.0.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0
  flutter_sheet_localization_generator: ^1.2.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true
