// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'localization.dart';

// **************************************************************************
// SheetLocalizationGenerator
// **************************************************************************

class AppLocalizations {
  AppLocalizations(this.locale) : this.labels = languages[locale];

  final Locale locale;

  static final Map<Locale, AppLocalizations_Labels> languages = {
    Locale.fromSubtags(languageCode: "en"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play count",
      stopCount: "Stop count",
      changeTitle: "Change title",
    ),
    Locale.fromSubtags(languageCode: "ja"): AppLocalizations_Labels(
      title: "Idea note",
      save: "保存",
      playCount: "カウント開始",
      stopCount: "カウント終了",
      changeTitle: "タイトル変更",
    ),
    Locale.fromSubtags(languageCode: "af"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "telling spel",
      stopCount: "telling stop",
      changeTitle: "verandering titel",
    ),
    Locale.fromSubtags(languageCode: "sq"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Luaj numërimin",
      stopCount: "Stop numërimin",
      changeTitle: "Ndryshimi Titulli",
    ),
    Locale.fromSubtags(languageCode: "am"): AppLocalizations_Labels(
      title: "Idea note",
      save: "አስቀምጥ",
      playCount: "ጨዋታ ብዛት",
      stopCount: "አቁም ቆጠራ",
      changeTitle: "ለውጥ ርዕስ",
    ),
    Locale.fromSubtags(languageCode: "ar"): AppLocalizations_Labels(
      title: "Idea note",
      save: "حفظ",
      playCount: "اللعب العد",
      stopCount: "توقف العد",
      changeTitle: "غير العنوان",
    ),
    Locale.fromSubtags(languageCode: "hy"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Պահպանել",
      playCount: "Խաղալ հաշվիչ",
      stopCount: "կանգառը հաշվիչ",
      changeTitle: "փոփոխություն վերնագիր",
    ),
    Locale.fromSubtags(languageCode: "az"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Yadda saxla",
      playCount: "Play count",
      stopCount: "Stop sayı",
      changeTitle: "Change adı",
    ),
    Locale.fromSubtags(languageCode: "eu"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play-kontaketa",
      stopCount: "Stop zenbaketa",
      changeTitle: "Aldaketa izenburua",
    ),
    Locale.fromSubtags(languageCode: "be"): AppLocalizations_Labels(
      title: "Idea note",
      save: "захаваць",
      playCount: "колькасць Play",
      stopCount: "спыніць лічыльнік",
      changeTitle: "змяніць назву",
    ),
    Locale.fromSubtags(languageCode: "bn"): AppLocalizations_Labels(
      title: "Idea note",
      save: "সংরক্ষণ",
      playCount: "প্লে গণনা",
      stopCount: "স্টপ গণনা",
      changeTitle: "শিরোনাম পরিবর্তন",
    ),
    Locale.fromSubtags(languageCode: "bs"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "play count",
      stopCount: "Stop posjeta",
      changeTitle: "Promijeni naslov",
    ),
    Locale.fromSubtags(languageCode: "bg"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Запази",
      playCount: "брой на възпроизвеждане",
      stopCount: "Stop брой",
      changeTitle: "Промени заглавието",
    ),
    Locale.fromSubtags(languageCode: "ca"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Desar",
      playCount: "vegades jugat",
      stopCount: "de recompte de detenció",
      changeTitle: "Canviar el títol",
    ),
    Locale.fromSubtags(languageCode: "ceb"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Luwasa",
      playCount: "play count",
      stopCount: "stop count",
      changeTitle: "Change titulo",
    ),
    Locale.fromSubtags(languageCode: "zh", countryCode: "CN"):
        AppLocalizations_Labels(
      title: "Idea note",
      save: "保存",
      playCount: "播放计数",
      stopCount: "停止计数",
      changeTitle: "更改标题",
    ),
    Locale.fromSubtags(languageCode: "zh", countryCode: "TW"):
        AppLocalizations_Labels(
      title: "Idea note",
      save: "保存",
      playCount: "播放計數",
      stopCount: "停止計數",
      changeTitle: "更改標題",
    ),
    Locale.fromSubtags(languageCode: "co"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Cruciani",
      playCount: "Dragoni Play",
      stopCount: "Dragoni Stop",
      changeTitle: "Cambia titre",
    ),
    Locale.fromSubtags(languageCode: "hr"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Uštedjeti",
      playCount: "Odbrojavanja",
      stopCount: "zaustavljanje broj",
      changeTitle: "promjena naslova",
    ),
    Locale.fromSubtags(languageCode: "cs"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Uložit",
      playCount: "Počet Play",
      stopCount: "Počet zastavení",
      changeTitle: "změna názvu",
    ),
    Locale.fromSubtags(languageCode: "da"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Gemme",
      playCount: "Afspil tæller",
      stopCount: "Stop tælling",
      changeTitle: "Skift titel",
    ),
    Locale.fromSubtags(languageCode: "nl"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Opslaan",
      playCount: "count Play",
      stopCount: "count stop",
      changeTitle: "De titel wijzigen",
    ),
    Locale.fromSubtags(languageCode: "eo"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Savi",
      playCount: "teatraĵo grafo",
      stopCount: "Stop grafo",
      changeTitle: "ŝanĝo titolo",
    ),
    Locale.fromSubtags(languageCode: "et"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Salvesta",
      playCount: "Esituskordi",
      stopCount: "Stopp count",
      changeTitle: "Muuda pealkiri",
    ),
    Locale.fromSubtags(languageCode: "fi"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Tallentaa",
      playCount: "Pelien määrä",
      stopCount: "Lopeta count",
      changeTitle: "muutos otsikko",
    ),
    Locale.fromSubtags(languageCode: "fr"): AppLocalizations_Labels(
      title: "Idea note",
      save: "sauvegarder",
      playCount: "nombre de jeux",
      stopCount: "comptage arrêt",
      changeTitle: "changement de titre",
    ),
    Locale.fromSubtags(languageCode: "fy"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Rêde",
      playCount: "play count",
      stopCount: "Stopje count",
      changeTitle: "Change titel",
    ),
    Locale.fromSubtags(languageCode: "gl"): AppLocalizations_Labels(
      title: "Idea note",
      save: "gardar",
      playCount: "Número de xogo",
      stopCount: "Conta parada",
      changeTitle: "cambio de título",
    ),
    Locale.fromSubtags(languageCode: "ka"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Გადარჩენა",
      playCount: "Play რაოდენობა",
      stopCount: "Stop რაოდენობა",
      changeTitle: "შეცვლა დასახელება",
    ),
    Locale.fromSubtags(languageCode: "de"): AppLocalizations_Labels(
      title: "Idea note",
      save: "speichern",
      playCount: "Spielzähler",
      stopCount: "Stop-Zählung",
      changeTitle: "Ändere den Titel",
    ),
    Locale.fromSubtags(languageCode: "el"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Αποθηκεύσετε",
      playCount: "καταμέτρηση Play",
      stopCount: "καταμέτρηση Διακοπή",
      changeTitle: "Αλλαγή τίτλου",
    ),
    Locale.fromSubtags(languageCode: "gu"): AppLocalizations_Labels(
      title: "Idea note",
      save: "સેવ",
      playCount: "રમો ગણતરી",
      stopCount: "રોકો ગણતરી",
      changeTitle: "શીર્ષક બદલવા",
    ),
    Locale.fromSubtags(languageCode: "ht"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Jwe konte",
      stopCount: "One Stop konte",
      changeTitle: "Chanje tit",
    ),
    Locale.fromSubtags(languageCode: "ha"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Ajiye",
      playCount: "play count",
      stopCount: "Tsaida count",
      changeTitle: "Change suna",
    ),
    Locale.fromSubtags(languageCode: "haw"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play helu",
      stopCount: "Stop helu",
      changeTitle: "Change inoa",
    ),
    Locale.fromSubtags(languageCode: "he"): AppLocalizations_Labels(
      title: "Idea note",
      save: "להציל",
      playCount: "ספירת Play",
      stopCount: "ספירת Stop",
      changeTitle: "שינוי כותרת",
    ),
    Locale.fromSubtags(languageCode: "hi"): AppLocalizations_Labels(
      title: "Idea note",
      save: "सहेजें",
      playCount: "गिनती खेलना",
      stopCount: "बंद करो गिनती",
      changeTitle: "शीर्षक बदलें",
    ),
    Locale.fromSubtags(languageCode: "hmn"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Txuag",
      playCount: "Play count",
      stopCount: "nres count",
      changeTitle: "hloov npe",
    ),
    Locale.fromSubtags(languageCode: "hu"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Megment",
      playCount: "Játék számláló",
      stopCount: "A stop száma",
      changeTitle: "Főzz",
    ),
    Locale.fromSubtags(languageCode: "is"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Vista",
      playCount: "Spila telja",
      stopCount: "stöðva telja",
      changeTitle: "Breyta titli",
    ),
    Locale.fromSubtags(languageCode: "ig"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "play ọnụ",
      stopCount: "Kwụsị ọnụ",
      changeTitle: "ịgbanwe aha",
    ),
    Locale.fromSubtags(languageCode: "id"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Menyimpan",
      playCount: "count bermain",
      stopCount: "berhenti menghitung",
      changeTitle: "perubahan judul",
    ),
    Locale.fromSubtags(languageCode: "ga"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Sábháil",
      playCount: "count Play",
      stopCount: "Stop líon",
      changeTitle: "Athraigh teideal",
    ),
    Locale.fromSubtags(languageCode: "it"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Salva",
      playCount: "conteggio partite",
      stopCount: "conteggio arresto",
      changeTitle: "Cambia titolo",
    ),
    Locale.fromSubtags(languageCode: "jw"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Simpen",
      playCount: "count Play",
      stopCount: "Stop count",
      changeTitle: "Ganti title",
    ),
    Locale.fromSubtags(languageCode: "kn"): AppLocalizations_Labels(
      title: "Idea note",
      save: "ಉಳಿಸಿ",
      playCount: "ಪ್ಲೇ ಎಣಿಕೆ",
      stopCount: "ನಿಲ್ಲಿಸಿ ಎಣಿಕೆ",
      changeTitle: "ಬದಲಾವಣೆ ಶೀರ್ಷಿಕೆ",
    ),
    Locale.fromSubtags(languageCode: "kk"): AppLocalizations_Labels(
      title: "Idea note",
      save: "сақтау",
      playCount: "Play саны",
      stopCount: "Stop саны",
      changeTitle: "өзгерту атауы",
    ),
    Locale.fromSubtags(languageCode: "km"): AppLocalizations_Labels(
      title: "Idea note",
      save: "រក្សាទុក",
      playCount: "រាប់ចំនួនលេង",
      stopCount: "ការរាប់បញ្ឈប់",
      changeTitle: "ចំណងជើងផ្លាស់ប្តូរ",
    ),
    Locale.fromSubtags(languageCode: "ko"): AppLocalizations_Labels(
      title: "Idea note",
      save: "저장",
      playCount: "플레이 횟수",
      stopCount: "정지 횟수",
      changeTitle: "제목 변경",
    ),
    Locale.fromSubtags(languageCode: "ku"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Rizgarkirin",
      playCount: "count Play",
      stopCount: "count Stop",
      changeTitle: "Change title",
    ),
    Locale.fromSubtags(languageCode: "ky"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Оюндун саны",
      stopCount: "Stop саны",
      changeTitle: "өзгөртүү бойунча",
    ),
    Locale.fromSubtags(languageCode: "lo"): AppLocalizations_Labels(
      title: "Idea note",
      save: "ບັນທຶກ",
      playCount: "ນັບຫຼິ້ນ",
      stopCount: "ນັບຢຸດ",
      changeTitle: "ການປ່ຽນແປງຫົວຂໍ້",
    ),
    Locale.fromSubtags(languageCode: "la"): AppLocalizations_Labels(
      title: "Idea note",
      save: "salvare",
      playCount: "comitem ludere",
      stopCount: "comitem subsisto",
      changeTitle: "mutare titulum",
    ),
    Locale.fromSubtags(languageCode: "lv"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Saglabāt",
      playCount: "spēlēt skaits",
      stopCount: "Stop skaits",
      changeTitle: "Mainīt nosaukumu",
    ),
    Locale.fromSubtags(languageCode: "lt"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Sutaupyti",
      playCount: "Žaista kartų",
      stopCount: "Sustabdyti skaičius",
      changeTitle: "Pakeisti pavadinimas",
    ),
    Locale.fromSubtags(languageCode: "lb"): AppLocalizations_Labels(
      title: "Idea note",
      save: "spueren",
      playCount: "Leeschtung zielen",
      stopCount: "Stop zielen",
      changeTitle: "änneren Titel",
    ),
    Locale.fromSubtags(languageCode: "mk"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Зачувај",
      playCount: "Грофот игра",
      stopCount: "Стоп брои",
      changeTitle: "Наслов промени",
    ),
    Locale.fromSubtags(languageCode: "mg"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play fanisana",
      stopCount: "Stop fanisana",
      changeTitle: "Change anaram-boninahitra",
    ),
    Locale.fromSubtags(languageCode: "ms"): AppLocalizations_Labels(
      title: "Idea note",
      save: "jimat",
      playCount: "kiraan bermain",
      stopCount: "kiraan Stop",
      changeTitle: "Tukar tajuk",
    ),
    Locale.fromSubtags(languageCode: "ml"): AppLocalizations_Labels(
      title: "Idea note",
      save: "രക്ഷിക്കും",
      playCount: "പ്ലേ എണ്ണം",
      stopCount: "നിർത്തുക എണ്ണം",
      changeTitle: "മാറ്റുക ശീർഷകം",
    ),
    Locale.fromSubtags(languageCode: "mt"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Ħlief",
      playCount: "play għadd",
      stopCount: "għadd stop",
      changeTitle: "titolu bidla",
    ),
    Locale.fromSubtags(languageCode: "mi"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Tiaki",
      playCount: "Kia hia ngā tākaro",
      stopCount: "Kia hia ngā Kāti",
      changeTitle: "Huri taitara",
    ),
    Locale.fromSubtags(languageCode: "mr"): AppLocalizations_Labels(
      title: "Idea note",
      save: "जतन करा",
      playCount: "प्ले संख्या",
      stopCount: "संख्या थांबवा",
      changeTitle: "शीर्षक बदला",
    ),
    Locale.fromSubtags(languageCode: "mn"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play тоо",
      stopCount: "Stop тоо",
      changeTitle: "өөрчлөлтийн нэр",
    ),
    Locale.fromSubtags(languageCode: "my"): AppLocalizations_Labels(
      title: "Idea note",
      save: "ကြော်ငြာကို Save လုပ်ရန်",
      playCount: "Play စရေတွက်",
      stopCount: "stop ရေတွက်",
      changeTitle: "ပြောင်းလဲခြင်းခေါင်းစဉ်",
    ),
    Locale.fromSubtags(languageCode: "ne"): AppLocalizations_Labels(
      title: "Idea note",
      save: "सेव",
      playCount: "प्ले गणना",
      stopCount: "गणना स्टप",
      changeTitle: "शीर्षक परिवर्तन",
    ),
    Locale.fromSubtags(languageCode: "no"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Lagre",
      playCount: "play count",
      stopCount: "stopp tellingen",
      changeTitle: "Endre tittel",
    ),
    Locale.fromSubtags(languageCode: "ny"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "achiyesa Play",
      stopCount: "Lekani achiyesa",
      changeTitle: "Change mutu",
    ),
    Locale.fromSubtags(languageCode: "ps"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "play شمېرنې",
      stopCount: "Stop شمېرنې",
      changeTitle: "د بدلون سرليک",
    ),
    Locale.fromSubtags(languageCode: "fa"): AppLocalizations_Labels(
      title: "Idea note",
      save: "صرفه جویی",
      playCount: "تعداد بازی",
      stopCount: "تعداد توقف",
      changeTitle: "تغییر عنوان",
    ),
    Locale.fromSubtags(languageCode: "pl"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Zapisać",
      playCount: "Ilość play",
      stopCount: "Ilość przystanek",
      changeTitle: "Zmień tytuł",
    ),
    Locale.fromSubtags(languageCode: "pt"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Salve ",
      playCount: "Número de jogo",
      stopCount: "contagem parada",
      changeTitle: "mudança de título",
    ),
    Locale.fromSubtags(languageCode: "pa"): AppLocalizations_Labels(
      title: "Idea note",
      save: "ਸੰਭਾਲੋ",
      playCount: "ਪਲੇ ਗਿਣਤੀ",
      stopCount: "ਰੋਕੋ ਗਿਣਤੀ",
      changeTitle: "ਸਿਰਲੇਖ ਨੂੰ ਬਦਲੋ",
    ),
    Locale.fromSubtags(languageCode: "ro"): AppLocalizations_Labels(
      title: "Idea note",
      save: "salva",
      playCount: "Numar jocuri",
      stopCount: "Numar de oprire",
      changeTitle: "Schimbarea din titlu",
    ),
    Locale.fromSubtags(languageCode: "ru"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Сохранить",
      playCount: "Количество Play",
      stopCount: "Остановить счетчик",
      changeTitle: "Изменить название",
    ),
    Locale.fromSubtags(languageCode: "sm"): AppLocalizations_Labels(
      title: "Idea note",
      save: "vagana",
      playCount: "Play faitauga",
      stopCount: "Taofi le faitauga",
      changeTitle: "suiga Igoa",
    ),
    Locale.fromSubtags(languageCode: "gd"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play cunnt",
      stopCount: "Stop cunnt",
      changeTitle: "Atharrachadh tiotal a 'Chlàir",
    ),
    Locale.fromSubtags(languageCode: "sr"): AppLocalizations_Labels(
      title: "Idea note",
      save: "сачувати",
      playCount: "play count",
      stopCount: "стоп датотека",
      changeTitle: "Промени наслов",
    ),
    Locale.fromSubtags(languageCode: "st"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "count ya Play",
      stopCount: "setopong count ya",
      changeTitle: "fetola sehlooho",
    ),
    Locale.fromSubtags(languageCode: "sn"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "Play count",
      stopCount: "Stop count",
      changeTitle: "Change rokuremekedza",
    ),
    Locale.fromSubtags(languageCode: "sd"): AppLocalizations_Labels(
      title: "Idea note",
      save: "سانڍيو",
      playCount: "راند شمار",
      stopCount: "اسٽاپ شمار",
      changeTitle: "عنوان تبديل ڪريو",
    ),
    Locale.fromSubtags(languageCode: "si"): AppLocalizations_Labels(
      title: "Idea note",
      save: "සුරකින්න",
      playCount: "Play ගණන්",
      stopCount: "ගණන් නැවතුම්",
      changeTitle: "වෙනස් මාතෘකාව",
    ),
    Locale.fromSubtags(languageCode: "sk"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Uložiť",
      playCount: "počet Play",
      stopCount: "počet zastavenie",
      changeTitle: "zmena názvu",
    ),
    Locale.fromSubtags(languageCode: "sl"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Shrani",
      playCount: "Število predvajanj",
      stopCount: "Stop Število",
      changeTitle: "naslov sprememba",
    ),
    Locale.fromSubtags(languageCode: "so"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "play count",
      stopCount: "Stop count",
      changeTitle: "Change horyaalka",
    ),
    Locale.fromSubtags(languageCode: "es"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Salvar",
      playCount: "Veces jugado",
      stopCount: "de recuento de detención",
      changeTitle: "Cambiar el título",
    ),
    Locale.fromSubtags(languageCode: "su"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Simpen",
      playCount: "count Play",
      stopCount: "eureun count",
      changeTitle: "robah judul",
    ),
    Locale.fromSubtags(languageCode: "sw"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Save",
      playCount: "kuhesabu Play",
      stopCount: "Stop kuhesabu",
      changeTitle: "Badilisha jina",
    ),
    Locale.fromSubtags(languageCode: "sv"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Spara",
      playCount: "Antal gånger spelad",
      stopCount: "Stoppa räkningen",
      changeTitle: "Ändra titel",
    ),
    Locale.fromSubtags(languageCode: "tl"): AppLocalizations_Labels(
      title: "Idea note",
      save: "I-save ang",
      playCount: "Play Count",
      stopCount: "stop count",
      changeTitle: "Baguhin ang pamagat",
    ),
    Locale.fromSubtags(languageCode: "tg"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Захира",
      playCount: "ҳисоб Play",
      stopCount: "ҳисоб Қатъи",
      changeTitle: "Тағйирёбии унвони",
    ),
    Locale.fromSubtags(languageCode: "ta"): AppLocalizations_Labels(
      title: "Idea note",
      save: "சேமி",
      playCount: "ப்ளே எண்ணிக்கை",
      stopCount: "நிறுத்து எண்ணிக்கை",
      changeTitle: "மாற்றம் தலைப்பு",
    ),
    Locale.fromSubtags(languageCode: "te"): AppLocalizations_Labels(
      title: "Idea note",
      save: "సేవ్",
      playCount: "ప్లే లెక్కింపు",
      stopCount: "ఆపు లెక్కింపు",
      changeTitle: "మార్పు టైటిల్",
    ),
    Locale.fromSubtags(languageCode: "th"): AppLocalizations_Labels(
      title: "Idea note",
      save: "บันทึก",
      playCount: "นับ Play",
      stopCount: "นับหยุด",
      changeTitle: "เปลี่ยนชื่อ",
    ),
    Locale.fromSubtags(languageCode: "tr"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Kayıt etmek",
      playCount: "Çalma sayısı",
      stopCount: "Dur sayımı",
      changeTitle: "Başlığı değiştir",
    ),
    Locale.fromSubtags(languageCode: "uk"): AppLocalizations_Labels(
      title: "Idea note",
      save: "зберегти",
      playCount: "кількість Play",
      stopCount: "зупинити лічильник",
      changeTitle: "змінити назву",
    ),
    Locale.fromSubtags(languageCode: "ur"): AppLocalizations_Labels(
      title: "Idea note",
      save: "محفوظ کریں",
      playCount: "کھیلیں شمار",
      stopCount: "سٹاپ شمار",
      changeTitle: "تبدیلی عنوان",
    ),
    Locale.fromSubtags(languageCode: "uz"): AppLocalizations_Labels(
      title: "Idea note",
      save: "saqlash",
      playCount: "Play soni",
      stopCount: "stop soni",
      changeTitle: "o'zgartirish nomi",
    ),
    Locale.fromSubtags(languageCode: "vi"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Tiết kiệm",
      playCount: "count chơi",
      stopCount: "dừng đếm",
      changeTitle: "Thay đổi tiêu đề",
    ),
    Locale.fromSubtags(languageCode: "cy"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Cadw",
      playCount: "cyfrif chwarae",
      stopCount: "cyfrif stop",
      changeTitle: "teitl Newid",
    ),
    Locale.fromSubtags(languageCode: "xh"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Gcina",
      playCount: "Dlala count",
      stopCount: "Misa count",
      changeTitle: "Tshintsha isihloko",
    ),
    Locale.fromSubtags(languageCode: "yi"): AppLocalizations_Labels(
      title: "Idea note",
      save: "ראַטעווען",
      playCount: "שפּיל ציילן",
      stopCount: "האַלטן ציילן",
      changeTitle: "טוישן טיטל",
    ),
    Locale.fromSubtags(languageCode: "yo"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Fipamọ",
      playCount: "play ka",
      stopCount: "Da ka",
      changeTitle: "Change akọle",
    ),
    Locale.fromSubtags(languageCode: "zu"): AppLocalizations_Labels(
      title: "Idea note",
      save: "Londoloza",
      playCount: "ukubalwa kokudlala",
      stopCount: "Stop count",
      changeTitle: "Guqula isihloko",
    ),
  };

  final AppLocalizations_Labels labels;

  static AppLocalizations_Labels of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)?.labels;
}

class AppLocalizations_Labels {
  const AppLocalizations_Labels(
      {this.title,
      this.save,
      this.playCount,
      this.stopCount,
      this.changeTitle});

  final String title;

  final String save;

  final String playCount;

  final String stopCount;

  final String changeTitle;
}
